package com.sample.rules

import com.sample.Pessoa;
import com.sample.Sala;


rule "Ligar sistema"
	when 
		(
		($p: Pessoa(nome == "José") && $s: Sala(temperatura > 26, ligado == false)) ||
		($p: Pessoa(nome == "Manuel") && $s: Sala(temperatura > 21, ligado == false)) ||
		($p: Pessoa(nome == "Joaquim") && $s: Sala(temperatura > 17, ligado == false))
		);
	then	
		$s.setLigado(true);
		$s.setTemperatura($s.getTemperatura() - 1);
		update($s);
		
		System.out.println(String.format(" --> Sistema ligou devido a %s", $p.getNome()));
		System.out.println(String.format(" --> Temperatura alterou para %d\n\n", $s.getTemperatura()));
end


rule "Desligar sistema"
	when
		(
		($p: Pessoa(nome == "José") && $s: Sala(temperatura < 20, ligado == true)) ||
		($p: Pessoa(nome == "Manuel") && $s: Sala(temperatura < 18, ligado == true)) ||
		($p: Pessoa(nome == "Joaquim") && $s: Sala(temperatura < 11, ligado == true))
		);
	then		
		$s.setLigado(false);
		$s.setTemperatura($s.getTemperatura() + 1);
		update($s);
		
		System.out.println(String.format(" --> Sistema desligou devido a %s", $p.getNome()));
		System.out.println(String.format(" --> Temperatura alterou para %d\n\n", $s.getTemperatura()));
end





